library(readr)
babies <- read_table("babies.csv")
View(babies)
mean(babies$age)
mean(babies$age, trim = 0.5)
median(babies$age)
var(babies$age)
sd(babies$age)
mean(babies$weight)
mean(babies$weight, trim = 0.5)
median(babies$weight)
var(babies$weight)
sd(babies$weight)
savehistory("~/Milestones/Milestone 5 - Code to Submit.R")
