library(readr)
babies <- read_table("babies.csv")
View(babies)
plot(babies$height, babies$weight, main = "Babies Measurements", xlab = "Height (in inches)", ylab = "Weight (in ounces)")
cor(babies$height, babies$weight)
plot(babies$bwt, babies$gestation, main = "Babies", xlab = "Data for bwt", ylab = "Gestation Data")
cor(babies$bwt, babies$gestation)
plot(babies$age, babies$smoke, main = "Babies", xlab = "Age Data", ylab = "Smoke Data")
cor(babies$age, babies$smoke)
savehistory("~/Milestones/Milestone 6 - Code to Submit.R")
